### ISSUE TITLE
Unexpected output with custom format

### ISSUE THREAD

**Issue by nuklea** [tototoshi/scala-csv#141]
```scala

import com.github.tototoshi.csv.{CSVWriter, DefaultCSVFormat}
import play.api.libs.json.Json

implicit object MyCSVFormat extends DefaultCSVFormat {
  override val escapeChar: Char = '\\'
}

val writer = CSVWriter.open(new java.io.OutputStreamWriter(System.out))
writer.writeRow(Seq(1, Json.obj("created" -> System.currentTimeMillis().toString), ","))
import com.github.tototoshi.csv.{CSVWriter, DefaultCSVFormat}
```

returns `1,"{""created"":""1549966608854""}",","`, but I expect `1,"{\"created\":\"1549966608854\"}",","`

**Comment by kory33** [comment]
I suppose the argument passed to `.print` here
https://github.com/tototoshi/scala-csv/blob/0cba01ade701f39ecdd7cbcfcc5557aff99d1c72/src/main/scala/com/github/tototoshi/csv/CSVWriter.scala#L84

... is supposed to be `format.escapeChar` rather than `format.quoteChar`, although in the default formatter they are the same.

**Comment by tototoshi** [comment]
@kory33 Exactly! 👍 👍 👍
