### ISSUE TITLE
scala 3 snapshot?

### ISSUE THREAD

**Issue by pjfanning** [tototoshi/scala-csv#174]
Would it be possible to publish a snapshot for Scala 3.0.0-M3?

**Comment by mfirry** [comment]
I've played around and ported it to Scala 3 (mainly for fun). Have look if you want https://github.com/mfirry/scala-csv.
Also I'd like to know what @tototoshi thinks about my fork.

**Comment by tototoshi** [comment]
v1.3.7 has been released, supporting Scala 3.0.0-RC1.

**Comment by tototoshi** [comment]
@mfirry  Thank you very much. I hadn't learned about Scala 3.0 yet, so this was very helpful.
Since it is possible to build with Scala 3.0 without changing the current code, and since I am focusing on compatibility for this library, I'm not going to change the code right now. But I will refer to your code again when I have the timing to make the next big change.
