### ISSUE TITLE
There is no way to handle invalid lines

### ISSUE THREAD

**Issue by l15k4** [tototoshi/scala-csv#40]
Hey,

as CSVReader doesn't expose you to file lines as `String` but you just get a `List` of values, there is no way to deal with invalid input. You just find out that `header.size != values.size` which means that something wasn't escaped correctly for example, but you can't even log the invalid line, you don't get a chance to investigate why the input is invalid...

I think that developer should have an access to the raw line as a `String` and the best way to do it would be if `CsvReader.scala` was extendable, so that it'd have public constructor and public `parser` and `lineReader` so one could extend it and override `readNext` method for getting access to the raw input... 

It would be quite minimalistic change that would be extremely helpful, I could remove 3 workarounds already if I could extend CsvParser...

What do you think? I can submit a tested PR right away if you confirm it is a good idea, please let me know, thank you

**Comment by tototoshi** [comment]
Thanks for your feedback, but I don't want to change `parser` and `lineReader` to be public. They are just internal APIs for current implementation. 

CSVReader knows the input file is valid and can be read as csv file, but doesn't know whether the output is just you want. `header.size != values.size` is not the problem for CSVReader, because the input file is at least valid as csv.
