### ISSUE TITLE
Performance: please support parsing to Vector[String] rather than List[String]

### ISSUE THREAD

**Issue by benhutchison** [tototoshi/scala-csv#76]
When accessing a collections by numeric index, `Vector` has much better performance than `List`, effective constant time vs linear for List [http://docs.scala-lang.org/overviews/collections/performance-characteristics.html]. Indexed access is very common for CSV data.

It is unfortunate that CSVParser currently uses a Vector internally, but then converts to a less-optimal List [before returning to client](https://github.com/tototoshi/scala-csv/blob/master/src/main/scala/com/github/tototoshi/csv/CSVParser.scala#L280).  

It would be easy to support parsing to Vector by introducing a `parseVector`method that doesnt convert to List, and then calling that from a `parse`method returning `List`, to maintain compatiblity.

Happy to send a PR if you are open to this idea?

**Comment by tototoshi** [comment]
I think this is not so important from the point of view of performance, because the list of fields are not so long. 
However, it was a big mistake to use `List[String]` as the type of interface. It has no reason to be `List[String]`. I will change it to `Seq[String]` and use Vector as implementation in the future.

**Comment by tototoshi** [comment]
https://github.com/tototoshi/scala-csv/issues/99
